import React from 'react';
import { createRoot } from 'react-dom/client';
import { NotificationSettings } from '../components/NotificationSettings';
import { ThemeProvider } from '../contexts/ThemeContext';
import '@ovhcloud/ods-react/normalize-css';
import '@ovhcloud/ods-themes/default/css';
import '@ovhcloud/ods-themes/default/fonts';
import '../src/ui/theme/ods-dark.css';
import '../src/ui/theme/ods-light.css';
import '../styles/globals.css';
createRoot(document.getElementById('root')!).render(<ThemeProvider><div className="dark bg-slate-900 p-4 text-white"><NotificationSettings/></div></ThemeProvider>);
